In [2]:
import numpy as np
my_arr = np.arange(1000000)
my_list = list(range(1000000))

In [3]:
%time for _ in range(10):my_arr2 = my_arr*2

Wall time: 22.9 ms


In [4]:
%time for _ in range(10):my_list2 =[x * 2 for x in my_list]

Wall time: 807 ms


In [5]:
#从上面的结果可以看到，numpy数组算法速度更快

In [6]:
data = np.random.randn(2,3)
data

array([[-1.17566769, -1.17465686, -1.34805632],
       [ 0.20944522,  0.36423214, -1.22603672]])

In [7]:
data.shape

(2, 3)

In [8]:
data = np.arange(15)
data

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [9]:
data = [1,2,3,4,5]
np.array(data)

array([1, 2, 3, 4, 5])

In [10]:
data = {"name":"chen linfeng","age":14,"adress":"beijing"}
np.asarray(data)

array({'name': 'chen linfeng', 'age': 14, 'adress': 'beijing'},
      dtype=object)

In [11]:
data = np.array([1,2,3,5,6,7]).reshape(3,2)
np.ones_like(data)

array([[1, 1],
       [1, 1],
       [1, 1]])

In [12]:
# 创建N*N矩阵，对角线为1，其余位置为0
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
arr1 = np.array([1,2,3],dtype = np.float64)
arr1.dtype

dtype('float64')

In [14]:
# 通过ndarray的astype方法明确地将一个数组从一个dtype转换成另一个dtype
arr1 = arr1.astype(np.int64)
arr1.dtype

dtype('int64')

In [15]:
# 某字符串数组表示的全是数字，也可以用astype将其转换为数值形式
number_arr = np.array(["1","2.33","3","1.2"],dtype = np.string_)
number_arr

array([b'1', b'2.33', b'3', b'1.2'], dtype='|S4')

In [16]:
number_arr = number_arr.astype(float)
number_arr

array([1.  , 2.33, 3.  , 1.2 ])

In [17]:
# 大小相同的数组之间的比较会生成布尔值数组：
arr1 = np.array([[1,2,3,4,5],[3,1,23,1,1]])
arr2 = np.array([[2,3,3,1,6],[2,5,1,2,52]])
arr1 >arr2

array([[False, False, False,  True, False],
       [ True, False,  True, False, False]])

In [18]:
# 二维数组切片方式
arrd = np.array([[1,2,3],[4,5,6],[7,8,9]])
arrd

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
arrd[:2]#沿着第一个轴进行切片

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
arrd[:2,1:]
# 先切出前两行，在切出后两列

array([[2, 3],
       [5, 6]])

In [21]:
arrd[1,:2]
# 选取第二行的前两列

array([4, 5])

In [22]:
arrd[:2,2]
# 选取第三列前两行

array([3, 6])

In [23]:
# “只有冒号”表示选取整个轴
arrd[:,:1]
# 选取第一列

array([[1],
       [4],
       [7]])

In [24]:
arrd[2,:].reshape(1,3)

array([[7, 8, 9]])

In [25]:
arrd[2,:].reshape(1,3)

array([[7, 8, 9]])

In [26]:
data = np.array([1,2,3,5,6,7]).reshape(3,2)
np.ones_like(data)

array([[1, 1],
       [1, 1],
       [1, 1]])

In [27]:
# 创建N*N矩阵，对角线为1，其余位置为0
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [28]:
arr1 = np.array([1,2,3],dtype = np.float64)
arr1.dtype

dtype('float64')

In [29]:
# 通过ndarray的astype方法明确地将一个数组从一个dtype转换成另一个dtype
arr1 = arr1.astype(np.int64)
arr1.dtype

dtype('int64')

In [30]:
# 某字符串数组表示的全是数字，也可以用astype将其转换为数值形式
number_arr = np.array(["1","2.33","3","1.2"],dtype = np.string_)
number_arr

array([b'1', b'2.33', b'3', b'1.2'], dtype='|S4')

In [31]:
number_arr = number_arr.astype(float)
number_arr

array([1.  , 2.33, 3.  , 1.2 ])

In [32]:
# 大小相同的数组之间的比较会生成布尔值数组：
arr1 = np.array([[1,2,3,4,5],[3,1,23,1,1]])
arr2 = np.array([[2,3,3,1,6],[2,5,1,2,52]])
arr1 >arr2

array([[False, False, False,  True, False],
       [ True, False,  True, False, False]])

In [33]:
# 二维数组切片方式
arrd = np.array([[1,2,3],[4,5,6],[7,8,9]])
arrd

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [34]:
arrd[:2]#沿着第一个轴进行切片

array([[1, 2, 3],
       [4, 5, 6]])

In [35]:
arrd[:2,1:]
# 先切出前两行，在切出后两列

array([[2, 3],
       [5, 6]])

In [36]:
arrd[1,:2]
# 选取第二行的前两列

array([4, 5])

In [37]:
arrd[:2,2]
# 选取第三列前两行

array([3, 6])

In [38]:
# “只有冒号”表示选取整个轴
arrd[:,:1]
# 选取第一列

array([[1],
       [4],
       [7]])

In [39]:
arrd[2,:].reshape(1,3)

array([[7, 8, 9]])

In [40]:
temp = np.array([[[1,2,3,4],[3,4,5,67,]],[[1,2,3,4],[6,7,8,9]]])

In [41]:
temp.shape

(2, 2, 4)

In [42]:
temp[:1,:2,:2]

array([[[1, 2],
        [3, 4]]])

In [43]:
# 布尔值索引
names = np.array(["bob","joe","will","bob","will","joe","joe"])
data = np.random.randn(7,4)#生成正太分布的随机数据

In [44]:
names

array(['bob', 'joe', 'will', 'bob', 'will', 'joe', 'joe'], dtype='<U4')

In [45]:
data

array([[-0.53417266, -0.58789477, -0.748988  ,  0.38894463],
       [-0.81802424,  0.9166994 ,  0.13649811,  0.11072856],
       [ 0.03460116,  0.68764253, -0.24672482,  0.01467563],
       [ 0.79694882,  0.32035482, -0.53362021, -0.76503739],
       [-0.45657489,  0.25086198,  1.95882184, -0.05859888],
       [-0.69762522,  1.17984842,  0.1547857 , -1.31938581],
       [ 0.76066469,  1.82292324, -1.88401241, -1.51231025]])

In [46]:
# 假设每个名字都对应data数组中的一行，而我们想要选出对应于名字"Bob"的所有行
names == "bob"

array([ True, False, False,  True, False, False, False])

In [47]:
data[names=="bob"]

array([[-0.53417266, -0.58789477, -0.748988  ,  0.38894463],
       [ 0.79694882,  0.32035482, -0.53362021, -0.76503739]])

In [48]:
# 布尔型数组的长度必须跟被索引的轴长度一致。
data[names=="bob",2:]

array([[-0.748988  ,  0.38894463],
       [-0.53362021, -0.76503739]])

In [49]:
# 要选择除"Bob"以外的其他值，既可以使用不等于符号（!=），也可以通过~对条件
# 进行否定：~操作符用来反转条件
names !="bob"

array([False,  True,  True, False,  True,  True,  True])

In [50]:
data[names !="bob"]

array([[-0.81802424,  0.9166994 ,  0.13649811,  0.11072856],
       [ 0.03460116,  0.68764253, -0.24672482,  0.01467563],
       [-0.45657489,  0.25086198,  1.95882184, -0.05859888],
       [-0.69762522,  1.17984842,  0.1547857 , -1.31938581],
       [ 0.76066469,  1.82292324, -1.88401241, -1.51231025]])

In [51]:
data[~(names=="bob")]

array([[-0.81802424,  0.9166994 ,  0.13649811,  0.11072856],
       [ 0.03460116,  0.68764253, -0.24672482,  0.01467563],
       [-0.45657489,  0.25086198,  1.95882184, -0.05859888],
       [-0.69762522,  1.17984842,  0.1547857 , -1.31938581],
       [ 0.76066469,  1.82292324, -1.88401241, -1.51231025]])

In [52]:
cond = names =="bob"
data[~cond]

array([[-0.81802424,  0.9166994 ,  0.13649811,  0.11072856],
       [ 0.03460116,  0.68764253, -0.24672482,  0.01467563],
       [-0.45657489,  0.25086198,  1.95882184, -0.05859888],
       [-0.69762522,  1.17984842,  0.1547857 , -1.31938581],
       [ 0.76066469,  1.82292324, -1.88401241, -1.51231025]])

选取这三个名字中的两个需要组合应用多个布尔条件，使用&（和）、|（或）之类
的布尔算术运算符即可.Python关键字and和or在布尔型数组中无效。要使用&与|

In [53]:
mask = (names=="bob")|(names=="will")
mask

array([ True, False,  True,  True,  True, False, False])

In [54]:
data[mask]

array([[-0.53417266, -0.58789477, -0.748988  ,  0.38894463],
       [ 0.03460116,  0.68764253, -0.24672482,  0.01467563],
       [ 0.79694882,  0.32035482, -0.53362021, -0.76503739],
       [-0.45657489,  0.25086198,  1.95882184, -0.05859888]])

通过布尔型数组设置值

In [55]:
data[data<0]=0
data

array([[0.        , 0.        , 0.        , 0.38894463],
       [0.        , 0.9166994 , 0.13649811, 0.11072856],
       [0.03460116, 0.68764253, 0.        , 0.01467563],
       [0.79694882, 0.32035482, 0.        , 0.        ],
       [0.        , 0.25086198, 1.95882184, 0.        ],
       [0.        , 1.17984842, 0.1547857 , 0.        ],
       [0.76066469, 1.82292324, 0.        , 0.        ]])

通过一维布尔数组设置整行或列的值

In [56]:
data[names != "joe"] = 7
data

array([[7.        , 7.        , 7.        , 7.        ],
       [0.        , 0.9166994 , 0.13649811, 0.11072856],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [0.        , 1.17984842, 0.1547857 , 0.        ],
       [0.76066469, 1.82292324, 0.        , 0.        ]])

花式索引（Fancy indexing）是一个NumPy术语，它指的是利用整数数组进行索
引

In [57]:
arr = np.empty((8,4))
arr

array([[ 1.20392285e-311,  1.03753786e-321,  0.00000000e+000,
         0.00000000e+000],
       [ 8.92882247e+271,  1.16095484e-028, -1.06890137e-300,
        -7.54932431e-184],
       [ 3.63700147e-143, -4.54770264e-179, -2.35837288e+181,
        -4.89993801e-142],
       [-1.50229595e-010, -6.62138431e+190, -2.18623861e-122,
         3.11468770e-014],
       [-8.10545032e-030, -8.31813478e+200, -5.80087633e-078,
         4.23012367e+138],
       [-2.46340278e-145, -4.04552128e+229, -1.49543034e-010,
        -3.34240087e+186],
       [-3.58455030e-093,  4.15171506e+223,  3.04232387e-014,
         6.67269821e+135],
       [ 8.93176404e+271,  4.98131536e+151,  4.16348025e-057,
         4.70107596e+180]])

In [58]:
for i in range(8):
    arr[i] = i
    
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

为了以特定顺序选取行子集，只需传入一个用于指定顺序的整数列表或ndarray即
可：

In [59]:
arr[[4,3,0,6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [60]:
arr.shape


(8, 4)

In [61]:
arr[[-1,-2,-3]]

array([[7., 7., 7., 7.],
       [6., 6., 6., 6.],
       [5., 5., 5., 5.]])

一次传入多个索引数组会有一点特别。它返回的是一个一维数组，其中的元素对应
各个索引元组

In [62]:
arr = np.arange(32).reshape((8,4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [63]:
arr[[1,5,7,7],[0,3,1,3]]
# (1,0)位置是4，（7，3）位置是31

array([ 4, 23, 29, 31])

In [64]:
arr[[1,5,2,3]][:,[0,3,1,2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [ 8, 11,  9, 10],
       [12, 15, 13, 14]])

数组转置和轴对换,转置是重塑的一种特殊形式，它返回的是源数据的视图（不会进行任何复制操作）。数组不仅有transpose方法，还有一个特殊的T属性：

In [65]:
arr = np.arange(15).reshape(3,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [66]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [67]:
np.dot(arr,arr.T)
# np.dot计算矩阵内积

array([[ 30,  80, 130],
       [ 80, 255, 430],
       [130, 430, 730]])

对于高维数组，transpose需要得到一个由轴编号组成的元组才能对这些轴进行转置
（比较费脑子）

In [68]:
arr = np.arange(24).reshape(2,3,4)
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [69]:
arr.transpose((1,0,2))

array([[[ 0,  1,  2,  3],
        [12, 13, 14, 15]],

       [[ 4,  5,  6,  7],
        [16, 17, 18, 19]],

       [[ 8,  9, 10, 11],
        [20, 21, 22, 23]]])

相当于x轴与y轴互换，变成了(3,2,4)


In [70]:
arr.swapaxes(1,2)

array([[[ 0,  4,  8],
        [ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11]],

       [[12, 16, 20],
        [13, 17, 21],
        [14, 18, 22],
        [15, 19, 23]]])

In [71]:
arr.transpose()

array([[[ 0, 12],
        [ 4, 16],
        [ 8, 20]],

       [[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]]])

通用函数（即ufunc）是一种对ndarray中的数据执行元素级运算的函数。你可以将
其看做简单函数（接受一个或多个标量值，并产生一个或多个标量值）的矢量化包
装器。

In [72]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [73]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [74]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [75]:
x = np.random.randn(8)
y = np.random.randn(8)

In [76]:
x

array([ 1.1696873 ,  1.45176294, -0.2335597 , -1.82900496,  1.97694192,
        1.66508055,  1.45236041, -0.74508601])

In [77]:
y

array([ 1.15643305,  0.39910316,  0.70505884,  0.96712793,  1.11778339,
        0.29936873, -0.05231708, -0.31653735])

In [78]:
np.maximum(x,y)

array([ 1.1696873 ,  1.45176294,  0.70505884,  0.96712793,  1.97694192,
        1.66508055,  1.45236041, -0.31653735])

In [79]:
np.add(x,y)

array([ 2.32612035,  1.85086611,  0.47149914, -0.86187703,  3.09472531,
        1.96444928,  1.40004333, -1.06162337])

In [80]:
arr = np.random.randn(7)*5
arr

array([-9.64790519,  2.71990053, -3.41173604, -1.46519013,  2.9276541 ,
       -4.83308324,  0.68653273])

In [81]:
remainder,whole_spart = np.modf(arr)

In [82]:
remainder

array([-0.64790519,  0.71990053, -0.41173604, -0.46519013,  0.9276541 ,
       -0.83308324,  0.68653273])

In [83]:
whole_spart

array([-9.,  2., -3., -1.,  2., -4.,  0.])

In [84]:
np.sqrt(arr)

d:\python\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


array([       nan, 1.64921209,        nan,        nan, 1.71103889,
              nan, 0.82857271])

In [85]:
np.sqrt(arr,arr)

d:\python\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


array([       nan, 1.64921209,        nan,        nan, 1.71103889,
              nan, 0.82857271])