可以通过数组上的一组数学函数对整个数组或某个轴向的数据进行统计计算。
sum、mean以及标准差std等聚合计算（aggregation，通常叫做约简
（reduction））既可以当做数组的实例方法调用，也可以当做顶级NumPy函数使
用。

In [41]:
import numpy as np
arr = np.random.randn(5,4)
arr

array([[ 0.74415772,  0.3670418 , -0.94115819,  0.58347273],
       [ 0.22294427,  1.34043658, -1.65163212,  0.31327512],
       [-0.88503591, -0.05800313, -0.94006532, -0.11509892],
       [ 0.7399867 , -0.02337515,  1.79148604,  1.20284384],
       [-2.0740394 ,  0.35556125, -1.201525  ,  0.59878115]])

In [42]:
arr.mean()

0.01850270286198829

In [43]:
np.mean(arr)

0.01850270286198829

In [44]:
arr.sum()

0.3700540572397658

mean和sum这类的函数可以接受一个axis选项参数,用于计算该轴向上的统计值,
最终结果是一个少一维的数组

In [45]:
arr.mean(axis=0)

array([-0.25039732,  0.39633227, -0.58857892,  0.51665478])

In [46]:
arr.mean(axis=1)

array([ 0.18837851,  0.05625596, -0.49955082,  0.92773536, -0.5803055 ])

In [47]:
arr.sum(axis=0)

array([-1.25198662,  1.98166135, -2.94289459,  2.58327392])

In [48]:
arr.max(axis=0)

array([0.74415772, 1.34043658, 1.79148604, 1.20284384])

In [49]:
# 其他如cumsum和cumprod之类的方法则不聚合，而是产生一个由中间结果组成的数组
arr = np.array([1,2,3,4,5,6,7,8])
arr.cumsum()
#累计和

array([ 1,  3,  6, 10, 15, 21, 28, 36], dtype=int32)

In [50]:
arr.cumprod()
# 累积

array([    1,     2,     6,    24,   120,   720,  5040, 40320],
      dtype=int32)

在多维数组中，累加函数（如cumsum）返回的是同样大小的数组，但是会根据每
个低维的切片沿着标记轴计算部分聚类：

In [51]:
arr = np.array([[0,1,2],[3,4,5],[6,7,8]])
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [52]:
arr.cumsum(axis=0)
# 沿着列进行累和

array([[ 0,  1,  2],
       [ 3,  5,  7],
       [ 9, 12, 15]], dtype=int32)

In [53]:
arr.cumsum(axis=1)
# 沿着行

array([[ 0,  1,  3],
       [ 3,  7, 12],
       [ 6, 13, 21]], dtype=int32)

In [54]:
arr = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[7,8,9],[1,2,5],[1,2,3]]])
arr

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[7, 8, 9],
        [1, 2, 5],
        [1, 2, 3]]])

In [55]:
arr.cumsum(axis=0)

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[ 8, 10, 12],
        [ 5,  7, 11],
        [ 8, 10, 12]]], dtype=int32)

In [56]:
arr.cumsum(axis=1)

array([[[ 1,  2,  3],
        [ 5,  7,  9],
        [12, 15, 18]],

       [[ 7,  8,  9],
        [ 8, 10, 14],
        [ 9, 12, 17]]], dtype=int32)

In [57]:
arr.cumsum(axis=2)

array([[[ 1,  3,  6],
        [ 4,  9, 15],
        [ 7, 15, 24]],

       [[ 7, 15, 24],
        [ 1,  3,  8],
        [ 1,  3,  6]]], dtype=int32)

std:标准差

var:方差
argmin,argmax:最大元素和最小元素的索引

用于布尔型数组的方法：

上面这些方法中，布尔值会被强制转换为1（True）和0（False）。因此，sum
经常被用来对布尔型数组中的True值计数：

In [58]:
arr = np.random.randn(100)
(arr > 0).sum()

64

方法any和all，它们对布尔型数组非常有用。any用于测试数组中是否
存在一个或多个True，而all则检查数组中所有值是否都是True,这两个方法也能用于非布尔型数组，所有非0元素将会被当做True

In [59]:
bools = np.array([False,True,False,False])
bools.any()

True

In [60]:
bools.all()

False

NumPy数组也可以通过sort方法就地排序

In [61]:
arr = np.random.randn(6)
arr

array([-2.15480302,  0.07930954, -0.68774138, -1.28087641, -0.06537304,
        1.63098697])

In [62]:
arr.sort()

多维数组可以在任何一个轴向上进行排序，只需将轴编号传给sort即可

In [63]:
arr = np.random.randn(5,3)
arr

array([[ 0.71467568,  0.6601224 ,  0.74360128],
       [-0.4313078 ,  1.49410814,  0.09060215],
       [-1.70116757,  0.36295306,  0.37223698],
       [ 0.48395298, -0.59626041,  0.63393408],
       [ 1.1806306 ,  0.23691791, -0.25223835]])

In [64]:
arr.sort(1)
arr

array([[ 0.6601224 ,  0.71467568,  0.74360128],
       [-0.4313078 ,  0.09060215,  1.49410814],
       [-1.70116757,  0.36295306,  0.37223698],
       [-0.59626041,  0.48395298,  0.63393408],
       [-0.25223835,  0.23691791,  1.1806306 ]])