NumPy能够读写磁盘上的文本数据或二进制数据

np.save和np.load是读写磁盘数组数据的两个主要函数。默认情况下，数组是以未
压缩的原始二进制格式保存在扩展名为.npy的文件中的

In [7]:
import numpy as np
arr = np.arange(10)
arr
np.save("data\\some_array.npy",arr)

In [8]:
np.load("data\\some_array.npy")

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

通过np.savez可以将多个数组保存到一个未压缩文件中，将数组以关键字参数的形
式传入即可,加载.npz文件时，你会得到一个类似字典的对象，该对象会对各个数组进行延迟加
载：

In [9]:
np.savez("arr_archive.npz",a = arr,b = arr)

In [12]:
arch = np.load("arr_archive.npz")
arch["a"]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

要将数据压缩，可以使用numpy.savez_compressed

In [16]:
arch = np.savez_compressed("arr_compressed.npz",a=arr,b=arr)
np.load("arr_compressed.npz")["a"]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])