NumPy提供了一个用于矩阵乘法的
dot函数（既是一个数组方法也是numpy命名空间中的一个函数）：

In [3]:
import numpy as np
x = np.array([[1,2,3],[4,5,6]])
y = np.array([[6,23],[-1,7],[8,9]])

In [4]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
y

array([[ 6, 23],
       [-1,  7],
       [ 8,  9]])

In [6]:
x.dot(y)

array([[ 28,  64],
       [ 67, 181]])

In [7]:
np.dot(x,y)

array([[ 28,  64],
       [ 67, 181]])

In [8]:
np.dot(x,np.ones(3))

array([ 6., 15.])

In [9]:
np.ones(3)

array([1., 1., 1.])

@符（类似Python 3.5）也可以用作中缀运算符，进行矩阵乘法

In [10]:
x@np.ones(3)

array([ 6., 15.])

numpy.linalg中有一组标准的矩阵分解运算以及诸如求逆和行列式之类的东西

In [32]:
from numpy.linalg import inv,qr
x = np.random.randn(5,5)
mat = x.T.dot(x)
mat

array([[ 6.34809784, -0.78686547, -1.85889403, -1.84609279,  1.50664202],
       [-0.78686547,  1.64344971, -2.15646928,  2.02182094,  1.55188902],
       [-1.85889403, -2.15646928,  6.32276437, -1.73642374, -4.34028527],
       [-1.84609279,  2.02182094, -1.73642374,  6.63411106, -1.68958291],
       [ 1.50664202,  1.55188902, -4.34028527, -1.68958291,  5.3077929 ]])

In [33]:
inv(mat)
# 求逆

array([[   0.77405491,   10.22194335,   -2.59172038,   -5.37046844,
          -7.03723817],
       [  10.22194335,  196.58425141,  -55.08861836, -107.01118176,
        -139.48967998],
       [  -2.59172038,  -55.08861836,   16.59246277,   30.63954004,
          40.16363971],
       [  -5.37046844, -107.01118176,   30.63954004,   58.79274754,
          76.58181559],
       [  -7.03723817, -139.48967998,   40.16363971,   76.58181559,
         100.19005865]])

In [34]:
mat.dot(inv(mat))

array([[ 1.00000000e+00, -1.86001576e-15,  6.90528635e-15,
         5.05930084e-15,  6.52147716e-15],
       [-4.66325811e-15,  1.00000000e+00,  5.40909626e-15,
         7.69977377e-15,  2.51691487e-15],
       [ 6.80098470e-15, -3.81417150e-14,  1.00000000e+00,
        -1.24359457e-14, -7.63440810e-14],
       [-7.28514403e-15,  1.39216717e-13,  2.08231997e-14,
         1.00000000e+00,  3.07125698e-14],
       [-7.72249009e-16,  8.15621971e-14, -2.88943617e-15,
         2.81943733e-14,  1.00000000e+00]])

In [36]:
q,r = qr(mat)
r

array([[-7.07467450e+00,  5.19310505e-01,  3.56067205e+00,
         3.51606738e+00, -3.89097535e+00],
       [ 0.00000000e+00, -3.76787473e+00,  7.38126177e+00,
        -4.64053138e+00, -4.66212808e+00],
       [ 0.00000000e+00,  0.00000000e+00, -1.66584179e+00,
        -3.38552912e+00,  3.25752328e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        -3.46670408e+00,  2.65652959e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  5.19714904e-03]])

常用函数：

diag：以一维数组返回方阵的对角线元素（或非对角线元素），或将一维数组转换为方阵（非对角线为0）

trace：求对角线元素之和

det:求行列式

eig:求特征值，特征向量

pinv:计算矩阵的Moore-Penrose伪逆

qr:计算QR分解

svd:计算奇异值分解

solve:解线性方程组Ax = b,其中A为方阵

lstsq:计算Ax=b的最小二乘解

In [37]:
arr =np.random.randn(3,3)
arr

array([[-1.2304149 ,  0.11537916, -1.64875486],
       [ 0.65581391,  3.20042066,  0.75750131],
       [ 0.09709503,  0.27929515,  1.21310269]])

In [38]:
arr.diagonal()

array([-1.2304149 ,  3.20042066,  1.21310269])

In [39]:
arr.trace()

3.1831084563917402

In [40]:
from numpy.linalg import det
det(arr)

-4.389655241798746

伪随机数的生成
